# Generated by Django 3.0.3 on 2020-03-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo_perfil',
            field=models.CharField(choices=[('L', 'Lançador'), ('AP1', 'Aprovador Nível 1'), ('AP2', 'Aprovador Nível 2')], max_length=3),
        ),
    ]
