# Generated by Django 3.0.2 on 2020-02-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_dia', '0003_auto_20200220_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='movdodia',
            name='anexo',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
