# Generated by Django 3.0.3 on 2020-03-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_orcamento', '0005_cadastroorcamento_aprovacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroorcamento',
            name='aprovacao',
            field=models.BooleanField(default=False, verbose_name='Aprovação'),
        ),
    ]
