# Generated by Django 3.0.3 on 2020-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_orcamento', '0006_auto_20200303_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroOrcamento',
        ),
    ]
