# Generated by Django 3.0.3 on 2020-03-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estouro_orcamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroestouroorcamento',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'created'), (1, 'paid'), (2, 'fulfilled'), (3, 'cancelled'), (4, 'returned')], default=1),
            preserve_default=False,
        ),
    ]
