# Generated by Django 3.0.3 on 2020-03-05 19:18

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('estouro_orcamento', '0003_auto_20200304_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastroestouroorcamento',
            name='status',
            field=django_fsm.FSMIntegerField(choices=[(0, 'created'), (1, 'fulfilled'), (2, 'cancelled'), (3, 'returned')], default='criado', protected=True),
        ),
    ]
