# Generated by Django 3.0.3 on 2020-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0002_auto_20200312_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='status_contas_a_pagar',
            field=models.CharField(choices=[('C', 'Criado'), ('A1', 'Aprovação 1'), ('A2', 'Aprovação 2'), ('AP', 'Aprovado'), ('PG', 'Enviar para Pagamento'), ('BX', 'Baixado')], default='C', max_length=2),
        ),
    ]
