# Generated by Django 3.0.3 on 2020-04-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0005_auto_20200408_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='data_pagamento_contas_a_pagar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='ag_beneficiario_contas_a_pagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='banco_beneficiario_contas_a_pagar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contaapagar',
            name='cc_beneficiario_contas_a_pagar',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
