# Generated by Django 3.0.6 on 2021-09-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0008_auto_20210805_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='tipo_de_pagamento',
            field=models.CharField(choices=[('a_vista', 'A Vista'), ('cartao', 'Cartão')], default='C', max_length=7),
        ),
    ]
