# Generated by Django 3.0.3 on 2020-03-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centro_de_custo', '0002_auto_20200203_1808'),
        ('natureza_orcamentaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAPagar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caso_contas_a_pagar', models.CharField(max_length=100)),
                ('data_input_contas_a_pagar', models.DateField(auto_now=True)),
                ('correspondente_contas_a_pagar', models.CharField(max_length=100)),
                ('fornecedor_contas_a_pagar', models.CharField(max_length=100)),
                ('historico_contas_a_pagar', models.TextField(max_length=1000000)),
                ('valor_contas_a_pagar', models.DecimalField(decimal_places=2, max_digits=100)),
                ('conta_debito_contas_a_pagar', models.CharField(max_length=100)),
                ('banco_beneficiario_contas_a_pagar', models.CharField(max_length=100)),
                ('ag_beneficiario_contas_a_pagar', models.CharField(max_length=100)),
                ('cc_beneficiario_contas_a_pagar', models.CharField(max_length=100)),
                ('anexo_boleto_contas_a_pagar', models.FileField(upload_to='anexo_boleto/')),
                ('anexo_comprovante_contas_a_pagar', models.FileField(upload_to='anexo_comprovante/')),
                ('cliente_contas_a_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centro_de_custo.CentroDeCusto')),
                ('natureza_contas_a_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='natureza_orcamentaria.NaturezaOrcamentaria')),
            ],
        ),
    ]
