# Generated by Django 3.0.3 on 2020-04-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0003_contaapagar_status_contas_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaapagar',
            name='cofins_contas_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='css_contas_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='ir_contas_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='iss_contas_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='contaapagar',
            name='pis_contas_a_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
