# Generated by Django 3.0.3 on 2020-04-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0006_auto_20200409_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaapagar',
            name='status_contas_a_pagar',
            field=models.CharField(choices=[('C', 'Criado'), ('A1', 'Aprovação 1'), ('A2', 'Aprovação 2'), ('AP', 'Aprovado'), ('EF', 'Evolução Fiscal'), ('EFF', 'Eviar Financeiro'), ('MOV', 'Movimento do Dia'), ('BX', 'Baixado')], default='C', max_length=3),
        ),
    ]
