# Generated by Django 3.0.6 on 2021-08-05 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas_a_pagar', '0007_auto_20200409_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaapagar',
            name='ag_beneficiario_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='anexo_comprovante_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='banco_beneficiario_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='caso_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='cc_beneficiario_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='cofins_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='conta_debito_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='correspondente_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='css_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='fornecedor_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='ir_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='iss_contas_a_pagar',
        ),
        migrations.RemoveField(
            model_name='contaapagar',
            name='pis_contas_a_pagar',
        ),
    ]
