# Generated by Django 3.0.2 on 2020-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov_dia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movdodia',
            name='valor_prov',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
